const express = require("express");
const crypto = require("crypto");
const Order = require("../models/Order");
const { requireAuth } = require("../middleware/auth");

const router = express.Router();

// POST /api/payments/verify
// { razorpay_order_id, razorpay_payment_id, razorpay_signature }
//
// This is the step that actually matters for security: Razorpay's checkout
// `handler` callback on the frontend cannot be trusted on its own, because
// anyone can call it from devtools and claim a payment succeeded. The HMAC
// signature below is generated by Razorpay using your key_secret, which
// never reaches the browser — so only a real, completed payment can
// produce a signature that matches.
router.post("/verify", requireAuth("registered"), async (req, res, next) => {
  try {
    const { razorpay_order_id, razorpay_payment_id, razorpay_signature } = req.body;
    if (!razorpay_order_id || !razorpay_payment_id || !razorpay_signature) {
      return res.status(400).json({ error: "Missing Razorpay payment fields." });
    }

    const order = await Order.findOne({
      "razorpay.orderId": razorpay_order_id,
      farmer: req.auth.farmerDbId,
    });
    if (!order) {
      return res.status(404).json({ error: "Order not found for this payment." });
    }

    const expectedSignature = crypto
      .createHmac("sha256", process.env.RAZORPAY_KEY_SECRET)
      .update(`${razorpay_order_id}|${razorpay_payment_id}`)
      .digest("hex");

    if (expectedSignature !== razorpay_signature) {
      order.status = "failed";
      await order.save();
      return res.status(400).json({ error: "Payment signature verification failed." });
    }

    order.status = "paid";
    order.razorpay.paymentId = razorpay_payment_id;
    order.razorpay.signature = razorpay_signature;
    await order.save();

    res.json({ ok: true, order });
  } catch (err) {
    next(err);
  }
});

module.exports = router;
